phrase = {
"Can you": "@$01",
"Will you": "@$02",
"Take care.": "@$03",
"Do you like" : "@$04",
"Do you want to" : "@$05",
"Do you have": "@$06",
"How are you?": "@$07",
"What's up?": "@$08",
"Nice to meet you.": "@$09",
"Have a good day.": "@$10",
"See you later.": "@$11",
"I don't know.": "@$12",
"I don't understand.": "@$13",
"I don't agree.": "@$14",
"Can you help me?": "@$15",
"Can I have a moment of your time?": "@$16",
"May I speak with you?": "@$17",
"Where are you from?": "@$18",
"What do you do?": "@$19",
"What's your name?": "@$20",
"How old are you?": "@$21",
"What's your favorite": "@$22",
"What's the matter?": "@$23",
"What's the problem?": "@$24",
"What's going on?": "@$25",
"What's happening?": "@$26",
"What's your opinion?": "@$27",
"What do you think?": "@$28",
"How do you feel about": "@$29",
"What do you think about": "@$30",
"Do you mind if I": "@$31",
"Can I ask you a question?": "@$32",
"Do you mind answering a question?": "@$33",
"Do you have a minute?": "@$34",
"Can we talk?": "@$35",
"Do you want to talk about it?": "@$36",
"What's your favorite movie?": "@$37",
"What's your favorite book?": "@$38",
"What's your favorite music?": "@$39",
"What's your favorite food?": "@$40",
"What's your favorite color?": "@$41",
"What's your favorite hobby?": "@$42",
"Do you have any plans for the weekend?": "@$43",
"Do you have any plans for tonight?": "@$44",
"What are you doing later?": "@$45",
"Do you want to come with me?": "@$46",
"Do you want to join us?": "@$47",
"Do you want to hang out?": "@$48",
"Do you want to grab a drink?": "@$49",
"Do you want to grab a bite to eat?": "@$50",
"Do you want to go see a movie?": "@$51",
"Do you have any recommendations?": "@$52",
"What do you suggest?": "@$53",
"What do you recommend?": "@$54",
"Where do you want to go?": "@$55",
"Where do you want to eat?": "@$56",
"What do you want to do?": "@$57",
"What do you feel like doing?": "@$58",
"How do you feel?": "@$59",
"Are you feeling okay?": "@$60",
"Are you feeling better?": "@$61",
"In this post, we will discuss": "@$62",
"Let's dive into": "@$63",
"Here's what you need to know": "@$64",
"My thoughts on": "@$65",
"How to [insert topic]": "@$66",
"The ultimate guide to": "@$67",
"Why [insert topic] matters": "@$68",
"A deep dive into": "@$69",
"The benefits of": "@$70",
"A comprehensive overview of": "@$71",
"A step-by-step guide to": "@$72",
"How to get started with": "@$73",
"The importance of": "@$74",
"The power of": "@$75",
"An expert's perspective on": "@$76",
"A personal story about": "@$77",
"The truth about": "@$78",
"A beginner's guide to": "@$79"}
